jimmy_gym_homepage:
    pattern:  /
    defaults: { _controller: JimmyGymBundle:Default:index }
    
jimmy_gym_products:
    pattern:  /products
    defaults: { _controller: JimmyGymBundle:Default:products }
    
jimmy_gym_register:
    pattern:  /register
    defaults: { _controller: JimmyGymBundle:Default:register }
    
jimmy_gym_profile:
    pattern:  /profile
    defaults: { _controller: JimmyGymBundle:Default:profile }            