parameters:
#    jimmy_gym.example.class: Jimmy\GymBundle\Example

services:
#    jimmy_gym.example:
#        class: %jimmy_gym.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
